config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show]
    resources :categories,          only: [:show], param: :taxon_id
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  def option_type_presentation
    option_types.map(&:presentation)
  end

  def option_value_presentation(option_type_presentation)
    option_types.find_by(presentation: option_type_presentation).option_values.map(&:presentation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:taxon_id])
    @taxonomies = Spree::Taxonomy.eager_load(root: { children: :children })
    @products = @taxon.all_products.includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_RELATED_PRODUCTS_BY_THE_TAXON = 4

  def show
    @product = Spree::Product.find(params[:id])
    @products = @product.taxons.map do |taxon|
      [
        taxon.name.to_sym,
        taxon.products.where.not(id: @product.id).
          includes(master: [:default_price, :images]).
          sample(MAX_NUMBER_OF_RELATED_PRODUCTS_BY_THE_TAXON),
      ]
    end.to_h
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Potepanec"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def set_active(*args)
    args.each do |arg|
      return "active" if content_for?(arg)
    end
    ""
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def taxons_list(root_taxon)
    if root_taxon.root?
      taxons_list_content(root_taxon)
    else
      content_tag :ul, id: root_taxon.id, class: "collapse collapseItem" do
        taxons_list_content(root_taxon)
      end
    end
  end

  def taxons_list_content(root_taxon)
    taxons = root_taxon.children.map do |taxon|
      triangle = taxon.parent.root? ? nil : "fa fa-caret-right"
      hidden = !taxon.parent.root?
      content_tag :li do
        if taxon.leaf?
          link_to(potepan_category_path(taxon.id)) do
            content_tag(:i, nil, class: triangle, "aria-hidden" => hidden) +
            "#{taxon.name} (#{taxon.all_products.count})"
          end
        else
          link_to("javascript:;", { "data-toggle" => "collapse", "data-target" => "##{taxon.id}" }) do
            content_tag(:i, nil, class: ["fa fa-plus", triangle], "aria-hidden" => hidden) +
            "#{taxon.name} (#{taxon.all_products.count})"
          end + taxons_list(taxon)
        end
      end
    end
    safe_join(taxons, "\n")
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modals.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= set_active(:index) %>">
          <%= link_to("Home", potepan_root_path) %>
        </li>
        <li class="dropdown megaDropMenu <%= set_active(:cart_page, :product_grid_sidebar_left, :product_list_sidebar_left, :single_product) %>">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu row">
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products Grid View</li>
                <li class="<%= set_active(:product_grid_sidebar_left) %>"><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products List View</li>
                <li class="<%= set_active(:product_list_sidebar_left) %>"><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                <li class="listHeading">Others</li>
                <li><a href="single_product.html">Single Product</a></li>
                <li><a href="cart_page.html">Cart Page</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Checkout</li>
                <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                <li><a href="checkout_complete.html">Order Complete</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_top_bar.html.erb
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li><span><a data-toggle="modal" href='#login'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span></li>
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>Item(s) in your cart</li>
              <li>
                <a href="#">
                  <div class="media">
                    <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                    <div class="media-body">
                      <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="media">
                    <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                    <div class="media-body">
                      <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <div class="btn-group" role="group" aria-label="...">
                  <button type="button" class="btn btn-default">Shopping Cart</button>
                  <button type="button" class="btn btn-default">Checkout</button>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= yield :head %>
  </head>
  <body>
    <div class="main-wrapper">
      <!-- HEADER -->
      <div class="header clearfix">
        <!-- TOPBAR -->
        <%= render 'layouts/top_bar' %>
        <!-- NAVBAR -->
        <%= render 'layouts/navbar' %>
      </div>
      <%= yield %>
      <!-- FOOTER -->
      <!-- COPY RIGHT -->
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modals' %>
    <%= yield :view_modal %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_root_path) %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_partners_logos.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name)%>
<% provide(:product_grid_sidebar_left, true) %>

<!-- LIGHT SECTION -->
<%= render 'potepan/categories/light_section', taxon: @taxon %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to potepan_category_path(@taxonomies.first.root.id) do %>
              All products <span>(<%= Spree::Product.count %>)</span>
            <% end %>
          </div>
        </div>
        <% @taxonomies.each do |taxonomy|  %>
          <div class="panel panel-default">
            <div class="panel-heading"><%= taxonomy.name %></div>
            <div class="panel-body">
              <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
                <ul class="nav navbar-nav side-nav">
                  <%=  taxons_list(taxonomy.root) %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'">
                <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
              </button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'">
                <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
              </button>
            </div>
          </div>
        </div>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox">
                <%= link_to potepan_product_path(product.id) do %>
                  <div class="productImage clearfix">
                    <%= image_tag product.display_image.attachment(:product) %>
                  </div>
                  <div class="productCaption clearfix">
                    <h5><%= product.name %></h5>
                    <h3><%= product.display_price %></h3>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<%= render 'potepan/categories/partners_logos' %>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_root_path) %>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_product.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>Related Products</h4>
    </div>
  </div>
  <% products.keys.each do |taxon| %>
    <h4><%= taxon if products[taxon].present? %></h4>
    <div class="col-xs-12">
      <% products[taxon].each do |product| %>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="productBox">
            <%= link_to potepan_product_path(product.id) do %>
              <div class="productImage clearfix">
                <%= image_tag product.display_image.attachment(:product) %>
              </div>
              <div class="productCaption clearfix">
                <h5><%= product.name %></h5>
                <h3><%= product.display_price %></h3>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<% provide(:single_product, true) %>

<!-- LIGHT SECTION -->
<%= render 'potepan/products/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, i| %>
                  <div class="item<%= " active" if i.zero?  %>" data-thumb="<%= i %>">
                    <%= image_tag image.attachment(:large) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag image.attachment(:small) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <% @product.option_type_presentation.each do |type| %>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <% @product.option_value_presentation(type).each_with_index do |value, i| %>
                    <option value="<%= i %>"><%= value %></option>
                  <% end %>
                </select>
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'potepan/products/related_product',  products: @products %>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% provide(:title, "Cart Page") %>
<% provide(:cart_page, true) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <a href="index.html">Home</a>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>